version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    image:
      holorepository-ui-client
    ports:
      - "3000:3000"
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image:
      holorepository-ui-server
    ports:
      - "3001:3001"
