openapi: "3.0.2"

info:
  version: 1.0.0
  title: HoloStorage Accessor API
  description: APIs to access the FHIR resources and 3D models from HoloStorage

servers:
  - url: http://holostorage.azurewebsites.net/v1/

paths:
  /patients:
    get:
      summary: "Get patient's metadata based on id"
      description: "Obtain patient's information stored within HoloStorage, FHIR metadata and number of Holograms associated with the patients"
      parameters:
        - name: Patient ID
          in: query
          description: ID of patient to return
          schema:
            type: string
            example: 2321e0b8-99ea-4961-aab7-b65fbc8f9673
      responses:
        200:
          description: Successful pulling of patients metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patients'
        400:
          description: Unaccepted input
        404:
          description: Metadata of patients were not found

  /patients/{id}:
    get:
      summary: "Get details of a single patient"
      parameters:
        - in: path
          name: id
          required: true
          description: ID of patient to return
          schema:
            type: string
            example: 2321e0b8-99ea-4961-aab7-b65fbc8f9673
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        400:
          description: Unaccepted input
        404:
          description: Patient id cannot be found

  /holograms:
    get:
      summary: "Get holograms metadata based on id"
      description: "Obtain hologram information stored within HoloStorage, FHIR metadata and number of Holograms associated with the patients"
      parameters:
        - name: Hologram ID
          in: query
          description: ID of hologram to return
          schema:
            type: string
            example: 2321e0b8-99ea-4961-aab7-b65fbc8f9673
      responses:
        200:
          description: Successfully found all hologram metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Holograms'
        400:
          description: Unaccepted input
        404:
          description: Metadata of holograms were not found

  /holograms/{id}:
    get:
      summary: "Get details of a single hologram"
      parameters:
        - in: path
          name: id
          required: true
          description: ID of hologram to return
          schema:
            type: string
            example: 2321e0b8-99ea-4961-aab7-b65fbc8f9673
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hologram'
        400:
          description: Unaccepted input
        404:
          description: Patient id cannot be found


components:
  schemas:
    Patients:
      title: Array of patients
      description: An array of patients metadata
      type: array
      items:
        $ref: '#/components/schemas/Patient'

    Patient:
      title: Patient metadata
      description: Metadata of a single patient
      type: object
      properties:
        id:
          type: string
          example: 2321e0b8-99ea-4961-aab7-b65fbc8f9673
        name:
          type: string
          example: Bob Dylan
        firstName:
          type: string
          example: Bob
        lastName:
          type: string
          example: Dylan
        gender:
          type: string
          example:
        birthDate:
          type: string
          format: date

    Holograms:
      title: Holograms
      type: array
      items:
        $ref: '#/components/schemas/Hologram'

    Hologram:
      title: Hologram
      type: object
      properties:
        id:
          type: string
          example: 2321e0b8-99ea-4961-aab7-b65fbc8f9673
        title:
          type: string
          example: Malformed hip bones
        author:
          type: string
          description: Who and/or what authored the Hologram
          example: Bone segmentation pipeline
        description:
          type: string
          example: Malformed hip bones on a 8 year old child
        modality:
          type: string
          example: CT scan
        size:
          type: integer
          example: 5120
        creation:
          type: string
          format: date-time
          example: 5120
        uriEndpoint:
          type: string
          example: https://holoblob.blob.core.windows.net/test/BrainScan-18486331-1234-5678-9101-fcac6b7d8c29.glb
        contentType:
          type: string
          example: application/octet-stream